# -*- coding: utf-8 -*-
"""Project alpro soal 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMgr0R7u41cTMJUr5xlYQJQIY9FfeOt5
"""

#program 4
nip = input("Masukkan NIP ASN: ")

if len(nip) != 18 or not nip.isdigit():
    print("Error: NIP harus terdiri dari tepat 18 digit angka.")
else:
    tahun   = nip[0:4]
    bulan   = int(nip[4:6])
    tanggal = int(nip[6:8])

    if bulan < 1 or bulan > 12:
        print("Error: Bulan pada NIP tidak valid (harus 01–12).")
    else:
        if bulan in [1, 3, 5, 7, 8, 10, 12]:
            maks_hari = 31
        elif bulan in [4, 6, 9, 11]:
            maks_hari = 30
        elif bulan == 2:
            maks_hari = 29

        if tanggal < 1 or tanggal > maks_hari:
            print(f"Error: Tanggal pada NIP tidak valid untuk bulan ini (harus 01–{maks_hari:02d}).")
        else:
            if bulan == 1:
                nama_bulan = "Januari"
            elif bulan == 2:
                nama_bulan = "Februari"
            elif bulan == 3:
                nama_bulan = "Maret"
            elif bulan == 4:
                nama_bulan = "April"
            elif bulan == 5:
                nama_bulan = "Mei"
            elif bulan == 6:
                nama_bulan = "Juni"
            elif bulan == 7:
                nama_bulan = "Juli"
            elif bulan == 8:
                nama_bulan = "Agustus"
            elif bulan == 9:
                nama_bulan = "September"
            elif bulan == 10:
                nama_bulan = "Oktober"
            elif bulan == 11:
                nama_bulan = "November"
            elif bulan == 12:
                nama_bulan = "Desember"

            print(f"Tanggal lahir: {tanggal} {nama_bulan} {tahun}")
