# -*- coding: utf-8 -*-
"""PROJECT ALPRO NOMOR 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qHOXcAH-upvZ8idM2OTSO2MaAeAe10mM
"""

# Menghitung jumlah kalimat dan kata
teks = "Masukkan Teks"
jumlah_kata = len(teks.split())
jumlah_kalimat = teks.count(".")
print("Teks tersebut memuat", jumlah_kalimat,
      "kalimat dan", jumlah_kata, "kata.")

