# -*- coding: utf-8 -*-
"""PROJEK ALPRO SOAL 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13iVeStLeXb1AC15I3dKWVkNYIizgsEwK
"""

import math

# Fungsi
def hitung_interval(p_hat, n, alpha):

    if alpha == 0.05:
        z = 1.96
    elif alpha == 0.10:
        z = 1.645

    margin_error = z * math.sqrt((p_hat * (1 - p_hat)) / n)

    batas_bawah = p_hat - margin_error
    batas_atas = p_hat + margin_error

    return {
        "BB": batas_bawah,
        "BA": batas_atas
    }

# Input
p_hat = ("Input nilai p_hat")
n = ("Input nilai n")
alpha = ("Input nilai alpha")

# Validasi
if p_hat < 0 or p_hat > 1:
    print("Error: Proporsi sampel harus berada pada rentang 0 sampai 1")

elif n <= 0:
    print("Error: Ukuran sampel harus lebih dari 0")

elif alpha != 0.05 and alpha != 0.10:
    print("Error: Alpha harus bernilai 0.05 atau 0.10")

else:
    hasil = hitung_interval(p_hat, n, alpha)

    # Menampilkan Hasil
    print("Batas Bawah =", hasil["BB"])
    print("Batas Atas =", hasil["BA"])
    print("Interval konfidensi = (", round(hasil["BB"], 4), ",", round(hasil["BA"], 4), ")")
