# -*- coding: utf-8 -*-
"""Bentuk Umum nomor 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHo8zr65fpDfzo1-n5Ma86GpSiRGkKsn
"""

#bentuk umun
K1 = "masukkan teks."
K2 = 'Masukkan teks, "Masukkan teks."'
K3 = "\"Masukkan teks\""
K4 = "Masukkan teks."

print(K1)
print(K2)
print(K3)
print(K4)
